# Generated by Django 5.1.3 on 2024-12-01 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0004_remove_category_more_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
